name: mmdzz

on:
  workflow_dispatch:
  schedule:
     - cron: '05 7-15 * * *'
  watch:
    types: started
#env:
  #TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install -g npm
          npm update
      - name: '运行 【mmdzz】'
        if: env.MMDZZURL
        run: |
          node mmdzz.js
        env:
          MMDZZURL: ${{ secrets.MMDZZURL }}
          MMDZZHD: ${{ secrets.MMDZZHD }}
          YSMBODY: ${{ secrets.YSMBODY }}
          YSM2BODY: ${{ secrets.YSM2BODY }}
          YSMTX: ${{ secrets.YSMTX }}
          ysmbd: ${{ secrets.ysmbd }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
